### ISSUE TITLE
FBAudienceNetwork 4.8.0 framework fixes this bug.

### ISSUE THREAD

**Issue by mintakson** [MaxGabriel/FANInterstitialLogImpression#1]
Hi, MaxGabriel.
I have experienced exactly same problem on FBAudienceNetwork 4.7.1 and spent a couple of days to solve this problem.
Fortunately, this problem was resolved in FBAudienceNetwork 4.8.0, released on Nov 11, 2015. The change log says "Resolved a rare race condition in interstitial impression logging when using WebKit to render the interstitial (iOS 8 + 9 devices)."

Thanks!

**Comment by MaxGabriel** [comment]
Hi @mintakson. We ran into this issue as well, and I actually reported this to FAN https://developers.facebook.com/bugs/747553248722932/ for them to make the fix. We've done the following things to address it:
- We explicitly warn against using 4.7.0/4.7.1 from our iOS downloads page because of this bug
- For our stable SDK, we've tested against FAN 4.6.0 which we recommend as a download
- For our beta SDK, we've tested against FAN 4.8.0 which we recommend as a download
